sudo: required
services:
  - docker

before_install:
  - docker build -t fallingsappy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fallingsappy/react-test npm test

after_success:
  - docker build -t fallingsappy/multi-client ./client
  - docker build -t fallingsappy/multi-nginx ./nginx
  - docker build -t fallingsappy/multi-server ./server
  - docker build -t fallingsappy/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push fallingsappy/multi-client
  - docker push fallingsappy/multi-nginx
  - docker push fallingsappy/multi-server
  - docker push fallingsappy/multi-worker

deploy:
provider: elasticbeanstalk
region: "eu-west-3"
app: "multi-docker"
env: "Multidocker-env"
bucket_name: "elasticbeanstalk-eu-west-3-944205829190"
bucket_path: "docker-multi"
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
